version: '3.6'

services:
  db:
    container_name: open_fls_db
    image: mysql:8.4.0
    restart: always
    env_file: docker-compose.env
    volumes:
      - open-fls-db:/var/lib/mysql
    secrets:
      - db_root_password
      - db_password
      - db_user
    ports:
      - 3306:3306
      - 33060:33060
    command: --innodb-fast-shutdown=0

  adminer:
    container_name: open_fls_adminer
    image: adminer:4.8.1
    restart: always
    networks:
      - open-fls-network

networks:
  open-fls-network:
    internal: false

secrets:
  db_password:
    file: secrets/db_password.secret
  db_root_password:
    file: secrets/db_root_password.secret
  db_user:
    file: secrets/db_user.secret

volumes:
  open-fls-db:
