# Server Configuration
server.port=8081
server.forward-headers-strategy=FRAMEWORK
server.servlet.contextPath=/api

# JWT Configuration
jwt.private-key=classpath:private.key
jwt.public-key=classpath:public.key

# Logging Configuration
logging.performance=true
logging.file.name=/logs/open-fls-backend.log

# Spring JPA and Jackson Configuration
spring.jpa.hibernate.ddl-auto=update

# Custom OpenFLS Configuration
openfls.general.workdays.real=251
openfls.general.workdays.assumption=195